packages:
  - fixtures/*

strictPeerDependencies: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
shellEmulator: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
