packages:
  - fixtures/*

strictPeerDependencies: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
shellEmulator: true

overrides:
  '@eslint-community/eslint-utils': ^4.9.0
  '@typescript-eslint/types': ^8.46.4
  '@typescript-eslint/utils': ^8.46.4
  eslint: ^9.39.1
  tsx: ^4.20.6
catalogs:
  dev:
    '@antfu/ni': ^27.0.1
    '@eslint/config-inspector': ^1.3.0
    '@types/node': ^24.10.1
    bumpp: ^10.3.1
    eslint-typegen: ^2.3.0
    execa: ^9.6.0
    lint-staged: ^16.2.6
    pnpm-workspace-yaml: ^1.3.0
    simple-git-hooks: ^2.13.1
    tinyglobby: ^0.2.15
    tsdown: ^0.16.4
    tsx: ^4.20.6
    typescript: ^5.9.3
    vitest: ^4.0.9
  peer:
    eslint: ^9.39.1
    eslint-plugin-vuejs-accessibility: ^2.4.1
    vue: ^3.5.24
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@stylistic/eslint-plugin': ^5.5.0
    '@typescript-eslint/eslint-plugin': ^8.46.4
    '@typescript-eslint/parser': ^8.46.4

    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-vue: ^10.5.1
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.5.0
    local-pkg: ^1.1.2
    vue-eslint-parser: ^10.2.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
